import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Check, MapPin, Phone, Star } from "lucide-react";
import { amenities, rooms, address, executiveRoomReference } from "@/lib/content";
import { RoomCard } from "@/components/room-card";
import { BookingWidget } from "@/components/booking-widget";
import { EnquiryForm } from "@/components/enquiry-form";
import { BookingConfirm } from "@/components/booking-confirm";

type Props = { params: Promise<{ slug: string[] }> };

const pageContent: Record<string, { eyebrow: string; title: string; italic: string; copy: string; image: string; type?: string }> = {
  about: { eyebrow: "OUR STORY", title: "Hospitality,", italic: "written in the stars.", copy: "A 53-room resort-style address in Khargone, created for restful stays, joyful gatherings and attentive everyday hospitality.", image: "/images/lobby.jpg" },
  amenities: { eyebrow: "EVERYTHING, CONSIDERED", title: "All you need,", italic: "beautifully gathered.", copy: "From poolside afternoons to fast WiFi and thoughtful daily service, discover the comforts that shape your stay.", image: "/images/pool.jpg" },
  experience: { eyebrow: "LIVE A LITTLE SLOWER", title: "Days shaped", italic: "around you.", copy: "Breakfast without hurry. Time by the water. A game outdoors. Dinner with the people who matter.", image: "/images/pool.jpg" },
  restaurant: { eyebrow: "THE RESTAURANT", title: "Flavours worth", italic: "lingering over.", copy: "Our in-house multi-cuisine restaurant brings guests together over generous plates, familiar flavours and easy conversation.", image: "/images/restaurant.jpg" },
  menu: { eyebrow: "DINE AT NAKSHATRA", title: "A menu for", italic: "every gathering.", copy: "A structured digital menu will be added after the hotel shares its current dishes, descriptions and prices.", image: "/images/restaurant.jpg" },
  wedding: { eyebrow: "WEDDINGS AT NAKSHATRA", title: "Your day,", italic: "made luminous.", copy: "A ~5,500 sq ft banquet hall, lush lawns and thoughtful hospitality create a beautiful canvas for your celebration.", image: "/images/wedding.jpg", type: "wedding" },
  "conference-and-meetings": { eyebrow: "MEET & CONNECT", title: "Business, with", italic: "room to breathe.", copy: "Conference and meeting facilities supported by dining, accommodation, parking and an attentive team.", image: "/images/lobby.jpg", type: "conference" },
  "personal-party": { eyebrow: "PRIVATE OCCASIONS", title: "Gather your", italic: "favourite people.", copy: "Plan an intimate occasion with flexible spaces, in-house dining and warm hospitality.", image: "/images/wedding.jpg", type: "personal party" },
  "birthday-party": { eyebrow: "BIRTHDAY CELEBRATIONS", title: "Another year,", italic: "beautifully celebrated.", copy: "Bring together dining, décor-ready spaces and room for everyone you love.", image: "/images/wedding.jpg", type: "birthday party" },
  "pool-party": { eyebrow: "BY THE WATER", title: "Make a splash,", italic: "make a memory.", copy: "Plan a poolside gathering around Nakshatra’s outdoor pool and resort setting.", image: "/images/pool.jpg", type: "pool party" },
  offers: { eyebrow: "ROOM RATES", title: "Clear choices,", italic: "beautiful stays.", copy: "Compare the supplied Executive Room reference plans, inclusions, taxes and nightly totals before checking the current direct rate with the hotel.", image: "/images/hero-resort.jpg" },
  gallery: { eyebrow: "A GLIMPSE OF NAKSHATRA", title: "See yourself", italic: "here.", copy: "This preview gallery uses generic images. Your selected property photography will replace each frame without changing the layout.", image: "/images/hero-resort.jpg" },
  reviews: { eyebrow: "GUEST STORIES", title: "Kind words,", italic: "warm memories.", copy: "Only hotel-approved reviews from Google, Tripadvisor and direct guests will be displayed here.", image: "/images/lobby.jpg" },
  "famous-spots": { eyebrow: "AROUND KHARGONE", title: "Discover the", italic: "region.", copy: "A future local guide will feature confirmed attractions, travel times and helpful routes from Nakshatra.", image: "/images/hero-resort.jpg" },
  contact: { eyebrow: "COME, STAY A WHILE", title: "We are", italic: "here for you.", copy: address, image: "/images/lobby.jpg", type: "general enquiry" },
};

const legal: Record<string, { title: string; intro: string; sections: [string,string][] }> = {
  faq: { title: "Frequently asked questions", intro: "Helpful basics for planning your stay.", sections: [["Where is the hotel?", `${address}, approximately 3 km from Khargone Bus Stand.`],["What are check-in and check-out times?", "The supplied OTA listing shows check-in at 12:00 PM and check-out at 10:00 AM."],["Is breakfast included?", "The Executive Room is offered as room-only, breakfast-included, or breakfast plus lunch/dinner. Choose the relevant rate plan while booking."],["Does the hotel have pools?", "Yes. The property offers an infinity-edge outdoor pool plus separate indoor and children’s pool facilities."],["Can I plan a wedding or event?", "Yes. Nakshatra offers a ~5,500 sq ft banquet hall, lawns, wedding/event spaces and conference facilities."],["How do I book right now?", "Use WhatsApp or call +91 94250 88369 while live online payments are being connected."]] },
  "terms-conditions": { title: "Terms & conditions", intro: "A clear final policy should be reviewed by the hotel before payment launch.", sections: [["Reservations", "A reservation is only confirmed after the hotel issues a booking reference and confirms any required payment."],["Guest information", "Guests may be required to provide valid identification at check-in in line with applicable rules."],["Property use", "Guests are expected to use hotel facilities responsibly and follow safety directions from staff."]] },
  "privacy-policy": { title: "Privacy policy", intro: "How guest information will be handled when online booking goes live.", sections: [["Information collected", "Booking contact information, stay details and preferences may be collected to fulfil a reservation."],["Payments", "Card and UPI details will be handled by the payment provider; the hotel website should not store full payment credentials."],["Contact", "Privacy questions can be raised by calling the hotel directly."]] },
  "cancellation-refund-policy": { title: "Cancellation & refund policy", intro: "Final cutoff windows and refund rules must be confirmed by the hotel before accepting payments.", sections: [["Preview status", "This page is a content placeholder and does not create a binding cancellation policy."],["Refunds", "Any eligible refund terms, processing times and deposit conditions will be shown clearly before payment."],["Assistance", "For an existing offline reservation, contact the hotel by phone or WhatsApp."]] },
};

export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const key = slug[0]; const content = pageContent[key]; return { title: content ? `${content.title} ${content.italic}` : key.replaceAll("-"," "), description: content?.copy }; }

function PageHero({ content }: { content: (typeof pageContent)[string] }) { return <section className="page-hero"><img src={content.image} alt="Generic hotel placeholder"/><div className="page-hero-shade"/><div className="page-hero-copy"><p className="kicker">{content.eyebrow}</p><h1>{content.title}<br/><em>{content.italic}</em></h1><p>{content.copy}</p></div><span className="image-label">GENERIC IMAGE · PROPERTY PHOTO NEEDED</span></section>; }

export default async function AnyPage({ params }: Props) {
  const { slug } = await params; const key = slug[0];
  if (key === "booking" && slug[1] === "confirm") return <main className="subpage dark-top"><BookingConfirm/></main>;
  if (key === "booking" && slug[1] === "success") return <main className="subpage dark-top"><section className="booking-complete"><div className="success-ring"><Check/></div><h1>Reservation<br/><em>received.</em></h1><p>Reference: {slug[2] || "NKS-DEMO-001"}</p></section></main>;
  if (key === "rooms" && slug[1]) { const room = rooms.find(r => r.slug === slug[1]); if (!room) return notFound(); return <main className="subpage"><section className="room-detail-hero"><img src={room.image} alt={`Generic ${room.name} placeholder`}/><span className="image-label">GENERIC ROOM IMAGE · REPLACE WITH REAL {room.name.toUpperCase()}</span></section><section className="detail-layout section-shell"><div className="detail-copy"><p className="kicker">{room.eyebrow}</p><h1>{room.name.split(" ")[0]} <em>{room.name.split(" ").slice(1).join(" ")}</em></h1><p className="lead">{room.description}</p><div className="feature-list">{room.features.map(f => <span key={f}><Check/>{f}</span>)}</div><p>Each room listing will be enriched with confirmed measurements, bed configuration, occupancy, amenities and a complete real-photo gallery supplied by the hotel.</p></div><aside className="detail-book glass-panel"><p className="kicker">PREVIEW RATE FROM</p><b>₹{room.rate.toLocaleString("en-IN")}</b><small>per night · taxes and live availability pending</small><BookingWidget compact/></aside></section><section className="related section-shell"><h2>More ways <em>to stay.</em></h2><div className="room-grid">{rooms.filter(r => r.slug !== room.slug).slice(0,2).map(r => <RoomCard key={r.slug} room={r}/>)}</div></section></main>; }
  if (key === "rooms") return <main className="subpage"><PageHero content={{ eyebrow:"SIX WAYS TO STAY", title:"Find your", italic:"perfect retreat.", copy:"From efficient comfort to an expansive family setting, every room is a considered place to pause.", image:"/images/room-luxury.jpg" }}/><section className="all-rooms section-shell"><div className="room-grid">{rooms.map(r => <RoomCard key={r.slug} room={r}/>)}</div></section><div className="mid-book"><BookingWidget/></div></main>;
  if (legal[key]) { const item = legal[key]; return <main className="subpage dark-top"><section className="legal-page section-shell"><p className="kicker">NAKSHATRA HOTEL &amp; RESORT</p><h1>{item.title}</h1><p className="lead">{item.intro}</p><div>{item.sections.map(([h,p]) => <article key={h}><h2>{h}</h2><p>{p}</p></article>)}</div></section></main>; }
  const content = pageContent[key]; if (!content) return notFound();
  if (key === "gallery") return <main className="subpage"><PageHero content={content}/><section className="gallery-grid section-shell">{["hero-resort","room-classic","pool","wedding","restaurant","room-suite","lobby","room-family"].map((img,i)=><figure key={img}><img src={`/images/${img}.jpg`} alt="Generic gallery placeholder"/><figcaption>0{i+1} · Generic image placeholder</figcaption></figure>)}</section></main>;
  if (key === "amenities") return <main className="subpage"><PageHero content={content}/><section className="full-amenities section-shell"><p className="kicker">AT YOUR SERVICE</p><h2>Stay with <em>everything in reach.</em></h2><div>{amenities.map(([,name])=><article key={name}><span>✦</span><h3>{name}</h3></article>)}</div></section></main>;
  if (key === "reviews") return <main className="subpage"><PageHero content={content}/><section className="reviews-grid section-shell">{["A calm, comfortable stay with the spaces we needed to slow down.","A welcoming setting for a family celebration and time together.","Convenient for Khargone, with thoughtful hospitality throughout our stay."].map((q,i)=><blockquote key={q}><div><Star/><Star/><Star/><Star/><Star/></div><p>“{q}”</p><cite>Preview review {i+1} · Replace with approved testimonial</cite></blockquote>)}</section></main>;
  if (key === "offers") return <main className="subpage"><PageHero content={content}/><section className="rates-section section-shell"><div className="rates-heading"><div><p className="kicker">CONFIRMED OTA REFERENCE</p><h2>Executive Room<br/><em>rate plans.</em></h2></div><div className="room-facts"><span><b>{executiveRoomReference.maxGuests}</b> max guests</span><span><b>{executiveRoomReference.size}</b></span><span><b>{executiveRoomReference.bed}</b></span><span><b>{executiveRoomReference.bathrooms}</b> bathroom</span></div></div><p className="rate-source-note">{executiveRoomReference.sourceLabel}. OTA prices can change by date and availability; these are reference prices, not yet the hotel’s approved direct-booking tariff.</p><div className="rate-plan-grid">{executiveRoomReference.ratePlans.map(plan=><article key={plan.name}><p className="kicker">EXECUTIVE ROOM</p><h3>{plan.name}</h3><p>{plan.includes}</p><div className="plan-price"><span><small>ROOM RATE / NIGHT</small><b>₹{plan.rate.toLocaleString("en-IN")}</b></span><span><small>TAXES &amp; FEES / NIGHT</small><b>₹{plan.taxes.toLocaleString("en-IN")}</b></span></div><div className="plan-total"><span>Total per night</span><b>₹{(plan.rate + plan.taxes).toLocaleString("en-IN")}</b></div><a className="gold-button" href={`https://wa.me/919770370076?text=Hello%2C%20I%27d%20like%20to%20check%20the%20current%20${encodeURIComponent(plan.name)}%20rate%20for%20the%20Executive%20Room.`}>Check direct rate <ArrowRight/></a></article>)}</div><div className="rate-details"><div><p className="kicker">ROOM AMENITIES</p><div>{executiveRoomReference.amenities.map(item=><span key={item}><Check/>{item}</span>)}</div></div><div><p className="kicker">PROPERTY RULES</p><div>{executiveRoomReference.rules.map(item=><span key={item}><Check/>{item}</span>)}</div></div></div></section></main>;
  const showForm = !!content.type;
  return <main className="subpage"><PageHero content={content}/><section className="story-block section-shell"><div><p className="kicker">{key === "contact" ? "GET IN TOUCH" : "THE NAKSHATRA WAY"}</p><h2>{key === "contact" ? "Let’s plan your visit." : "Made for moments that matter."}</h2><p>{content.copy}</p>{key === "contact" && <div className="contact-list"><a href="tel:+919425088369"><Phone/>+91 94250 88369</a><a href="https://maps.google.com/?q=Nakshatra+Hotel+Resort+Khargone"><MapPin/>{address}</a></div>}</div>{showForm ? <EnquiryForm type={content.type}/> : <div className="story-image"><img src={key === "restaurant" ? "/images/restaurant.jpg" : key === "about" ? "/images/lobby.jpg" : "/images/pool.jpg"} alt="Generic property placeholder"/><span className="image-label">GENERIC IMAGE · REAL PROPERTY PHOTO NEEDED</span></div>}</section>{!showForm && <section className="mid-book"><BookingWidget/></section>}</main>;
}
