create table if not exists public.room_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null default '',
  base_price integer not null check (base_price >= 0),
  total_rooms integer not null default 15 check (total_rooms >= 0),
  max_guests integer not null default 2 check (max_guests > 0),
  active boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.meal_options (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  price_per_guest integer not null default 0 check (price_per_guest >= 0),
  description text not null default '',
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.availability (
  id bigint generated by default as identity primary key,
  room_slug text not null references public.room_categories(slug) on update cascade on delete cascade,
  date date not null,
  available_rooms integer not null check (available_rooms >= 0),
  price_override integer check (price_override is null or price_override >= 0),
  note text not null default '',
  updated_at timestamptz not null default now(),
  unique (room_slug, date)
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  status text not null default 'new' check (status in ('new', 'confirmed', 'checked-in', 'checked-out', 'cancelled')),
  source text not null default 'Website Direct',
  room_slug text not null references public.room_categories(slug) on update cascade,
  room_name text not null,
  guest_name text not null,
  phone text not null,
  email text not null default '',
  check_in date not null,
  check_out date not null,
  guests integer not null check (guests > 0),
  meal_plan text not null default 'Room only',
  total integer not null default 0 check (total >= 0),
  arrival text not null default '',
  requests text not null default '',
  payment_method text not null default 'Pay at hotel',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (check_out > check_in)
);

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  type text not null default 'general',
  name text not null,
  phone text not null,
  email text not null default '',
  preferred_date date,
  message text not null default '',
  status text not null default 'new' check (status in ('new', 'contacted', 'converted', 'closed')),
  source text not null default 'Website Direct',
  created_at timestamptz not null default now()
);

create index if not exists availability_date_idx on public.availability (date);
create index if not exists bookings_check_in_idx on public.bookings (check_in);
create index if not exists bookings_status_idx on public.bookings (status);
create index if not exists enquiries_status_idx on public.enquiries (status);

alter table public.room_categories enable row level security;
alter table public.meal_options enable row level security;
alter table public.availability enable row level security;
alter table public.bookings enable row level security;
alter table public.enquiries enable row level security;

revoke all on table public.room_categories, public.meal_options, public.availability, public.bookings, public.enquiries from anon, authenticated;
grant select, insert, update, delete on table public.room_categories, public.meal_options, public.availability, public.bookings, public.enquiries to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.room_categories (slug, name, description, base_price, total_rooms, max_guests, sort_order)
values
  ('executive', 'Executive Room', 'Effortless comfort for business and leisure travellers.', 2999, 15, 2, 0),
  ('deluxe', 'Deluxe Room', 'More room to unwind with attentive in-room service.', 3799, 15, 3, 1),
  ('family', 'Family Room', 'A comfortable setting for families and small groups.', 7499, 15, 4, 2),
  ('suite', 'Suite Room', 'A spacious retreat with a separate sitting area.', 6499, 15, 3, 3)
on conflict (slug) do nothing;

insert into public.meal_options (slug, name, price_per_guest, description)
values
  ('breakfast', 'Breakfast', 166, 'Breakfast per guest, per day'),
  ('lunch', 'Lunch', 350, 'Lunch per guest, per day'),
  ('dinner', 'Dinner', 350, 'Dinner per guest, per day')
on conflict (slug) do nothing;
